### ISSUE TITLE
[BUG] sidecasts via is/as always fail

### ISSUE THREAD

**Issue by gerlero** [hsutter/cppfront#127]
**Describe the bug**
When attempting to sidecast (in a scenario with multiple inheritance) using the `is`/`as` syntax, all cast attempts fail—even when an equivalent `dynamic_cast` would succeed.

**To Reproduce**
1. Sample code - distilled down to minimal essentials please
```cpp
struct B1 { virtual ~B1() = default; };

struct B2 { virtual ~B2() = default; };

struct D : B1, B2 {};

main: () -> int = {
    d: D = ();
    p: *B1 = d&;

    std::cout << p* is B2 << std::endl;
}
```
2. Command lines including which C++ compiler you are using
x86-64 gcc 12.2 with `-std=c++20` option

3. Expected result - what you expected to happen
Program compiles and outputs `1` (i.e., `p*` _is_ a `B2`)

4. Actual result/error
Program compiles but prints `0`

**Additional context**
The `cpp2::is` and `cpp2::as` overloads that would actually try a `dynamic_cast` in this situation are never considered because they are currently constrained to downcasts only (with `is_base_of` checks in their requires clauses).

EDIT: fix typo in code snippet

**Comment by hsutter** [comment]
Thanks @gerlero and @filipsajdak!

I think this is now fixed with #128, and I tried the example and it seems to be correct now.

**Comment by gerlero** [comment]
The `is` case seems to be fixed. However, the same sidecast with `as` is still failing.

Unfortunately, my example didn't explicitly cover that case (although replacing `is`->`as` in the snippet is enough; the cast will evaluate to `nullptr` even though it shouldn't). I can open a new issue for the `as` case if it helps with tracking.

**Comment by filipsajdak** [comment]
Yes, you are right. `as` will not work for sidecast. 

In https://github.com/hsutter/cppfront/pull/106 I have covered handling bad `as` casts. 

I have noticed that `as` for sidecast is missing - it requires bad cast handling. If the proposed solution for handling bad casts is accepted by @hsutter, I can provide a proper `as` cast.
